CREATE TABLE IF NOT EXISTS sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)     NOT NULL UNIQUE,
    password        VARCHAR(256)    NOT NULL,
    email           VARCHAR(128),
    system_role     VARCHAR(16)     NOT NULL DEFAULT 'USER',
    status          VARCHAR(16)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_group (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128)    NOT NULL,
    description     CLOB,
    org_code        VARCHAR(64)     UNIQUE,
    creator_id      BIGINT          NOT NULL,
    status          VARCHAR(16)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_member (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    role            VARCHAR(16)     NOT NULL DEFAULT 'MEMBER',
    joined_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(group_id, user_id)
);

CREATE TABLE IF NOT EXISTS knowledge_base (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128)    NOT NULL,
    description     CLOB,
    group_id        BIGINT          NOT NULL,
    evidence_threshold  DECIMAL(3,2) NOT NULL DEFAULT 0.50,
    chunk_strategy  VARCHAR(32)     NOT NULL DEFAULT 'PARAGRAPH',
    chunk_size      INT             NOT NULL DEFAULT 500,
    chunk_overlap   INT             NOT NULL DEFAULT 100,
    status          VARCHAR(16)     NOT NULL DEFAULT 'ACTIVE',
    creator_id      BIGINT          NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kb_member (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT       NOT NULL,
    user_id         BIGINT          NOT NULL,
    role            VARCHAR(16)     NOT NULL DEFAULT 'MEMBER',
    joined_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(knowledge_base_id, user_id)
);

CREATE TABLE IF NOT EXISTS document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT       NOT NULL,
    file_name       VARCHAR(256)    NOT NULL,
    file_format     VARCHAR(32)     NOT NULL,
    file_size       BIGINT          NOT NULL,
    storage_path    VARCHAR(512)    NOT NULL,
    ingestion_status VARCHAR(32)   NOT NULL DEFAULT 'PENDING',
    chunk_count     INT             DEFAULT 0,
    uploader_id     BIGINT          NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS document_chunk (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT          NOT NULL,
    knowledge_base_id BIGINT       NOT NULL,
    content         CLOB            NOT NULL,
    chunk_index     INT             NOT NULL,
    vector_id       VARCHAR(128),
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    knowledge_base_id BIGINT,
    model_provider  VARCHAR(32)     NOT NULL DEFAULT 'deepseek',
    title           VARCHAR(256),
    summary         CLOB,
    status          VARCHAR(16)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT          NOT NULL,
    role            VARCHAR(16)     NOT NULL,
    content         CLOB            NOT NULL,
    citations       CLOB,
    tool_calls      CLOB,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analysis_report (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path       VARCHAR(512)    NOT NULL,
    file_name       VARCHAR(256)    NOT NULL,
    provider        VARCHAR(32),
    session_id      VARCHAR(128),
    content         CLOB,
    file_size       BIGINT,
    file_category   VARCHAR(32),
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    token_hash      VARCHAR(256)    NOT NULL UNIQUE,
    expires_at      TIMESTAMP       NOT NULL,
    revoked         BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE document ADD COLUMN IF NOT EXISTS doi VARCHAR(256);
ALTER TABLE document ADD COLUMN IF NOT EXISTS authors VARCHAR(1024);
ALTER TABLE document ADD COLUMN IF NOT EXISTS publication_year INTEGER;
ALTER TABLE document ADD COLUMN IF NOT EXISTS journal VARCHAR(512);

CREATE TABLE IF NOT EXISTS research_note (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id            BIGINT,
    document_id         BIGINT,
    knowledge_base_id   BIGINT,
    user_id             BIGINT          NOT NULL,
    content             CLOB            NOT NULL,
    highlight           CLOB,
    start_offset        INT,
    end_offset          INT,
    tags                VARCHAR(256),
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
