package com.example.evimind.mapper;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import org.h2.jdbcx.JdbcDataSource;
import org.h2.tools.RunScript;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

class StandaloneSchemaPerformanceIndexTest {

  @Test
  void shouldIndexKnowledgeBaseFilterUsedByStandaloneChunkSearch() throws Exception {
    JdbcDataSource dataSource = new JdbcDataSource();
    dataSource.setURL(
        "jdbc:h2:mem:standalone_schema_"
            + UUID.randomUUID()
            + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE");
    dataSource.setUser("sa");

    try (Connection connection = dataSource.getConnection();
        InputStreamReader schema =
            new InputStreamReader(
                new ClassPathResource("schema-h2.sql").getInputStream(),
                StandardCharsets.UTF_8)) {
      RunScript.execute(connection, schema);

      Set<String> indexNames = new HashSet<>();
      try (ResultSet indexes =
          connection.getMetaData().getIndexInfo(null, null, "document_chunk", false, false)) {
        while (indexes.next()) {
          indexNames.add(indexes.getString("INDEX_NAME").toLowerCase());
        }
      }

      assertTrue(
          indexNames.contains("idx_chunk_kb_id"),
          "standalone chunk search requires an index on knowledge_base_id: " + indexNames);
    }
  }

  @Test
  void shouldUpgradeExistingChunkTableBeforeCreatingVersionedIndex() throws Exception {
    JdbcDataSource dataSource = new JdbcDataSource();
    dataSource.setURL(
        "jdbc:h2:mem:standalone_schema_upgrade_"
            + UUID.randomUUID()
            + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE");
    dataSource.setUser("sa");

    try (Connection connection = dataSource.getConnection();
        Statement statement = connection.createStatement()) {
      statement.execute(
          """
          CREATE TABLE document_chunk (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_id BIGINT NOT NULL,
            knowledge_base_id BIGINT NOT NULL,
            content CLOB NOT NULL,
            chunk_index INT NOT NULL,
            vector_id VARCHAR(128),
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
          )
          """);

      try (InputStreamReader schema =
          new InputStreamReader(
              new ClassPathResource("schema-h2.sql").getInputStream(),
              StandardCharsets.UTF_8)) {
        RunScript.execute(connection, schema);
      }

      try (ResultSet columns =
          connection
              .getMetaData()
              .getColumns(null, null, "document_chunk", "ingestion_version")) {
        assertTrue(columns.next(), "standalone schema must upgrade existing chunk tables");
      }

      Set<String> indexNames = new HashSet<>();
      try (ResultSet indexes =
          connection.getMetaData().getIndexInfo(null, null, "document_chunk", false, false)) {
        while (indexes.next()) {
          indexNames.add(indexes.getString("INDEX_NAME").toLowerCase());
        }
      }

      assertTrue(
          indexNames.contains("uk_document_chunk_version_index"),
          "versioned chunk index must be created after schema upgrade: " + indexNames);
    }
  }

  @Test
  void shouldCreateScheduledTaskTableUsedByStandaloneRuntime() throws Exception {
    JdbcDataSource dataSource = new JdbcDataSource();
    dataSource.setURL(
        "jdbc:h2:mem:standalone_scheduler_schema_"
            + UUID.randomUUID()
            + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE");
    dataSource.setUser("sa");

    try (Connection connection = dataSource.getConnection();
        InputStreamReader schema =
            new InputStreamReader(
                new ClassPathResource("schema-h2.sql").getInputStream(),
                StandardCharsets.UTF_8)) {
      RunScript.execute(connection, schema);

      try (ResultSet tables =
          connection.getMetaData().getTables(null, null, "scheduled_task", null)) {
        assertTrue(tables.next(), "standalone runtime scheduler requires scheduled_task table");
      }

      Set<String> indexNames = new HashSet<>();
      try (ResultSet indexes =
          connection.getMetaData().getIndexInfo(null, null, "scheduled_task", false, false)) {
        while (indexes.next()) {
          indexNames.add(indexes.getString("INDEX_NAME").toLowerCase());
        }
      }

      assertTrue(
          indexNames.contains("idx_scheduled_task_status"),
          "scheduler status filter requires an index: " + indexNames);
      assertTrue(
          indexNames.contains("idx_scheduled_task_type"),
          "scheduler task type filter requires an index: " + indexNames);
      assertTrue(
          indexNames.contains("idx_scheduled_task_next_run"),
          "scheduler due-task polling requires a next_run_at index: " + indexNames);
    }
  }
}
