ALTER TABLE document ADD COLUMN IF NOT EXISTS doi VARCHAR(256);
ALTER TABLE document ADD COLUMN IF NOT EXISTS authors VARCHAR(1024);
ALTER TABLE document ADD COLUMN IF NOT EXISTS publication_year INTEGER;
ALTER TABLE document ADD COLUMN IF NOT EXISTS journal VARCHAR(512);
